[features]
seeds = false
skip-lint = false
[programs.localnet]
token_contract = "BzVRmDPEmh9yLb9hC1CXGC9cNuwMM57bR3Dn2rxyPTfo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/daryltng/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
